name    'erwbgy-iptables'
version '0.3.1'
source 'git.com:erwbgy/puppet-iptables.git'
author 'Keith Burdis'
license 'Apache License, Version 2.0'
summary 'manage iptables allow and deny rules'
project_page 'https://github.com/erwbgy/puppet-iptables'
